name: Main Branch Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.10"
      run_tests: true

  docker-build-push:
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: atulsharmadochub/myapp
      tag: latest
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  docker-build-push-sha:
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: atulsharmadochub/myapp
      tag: sha-${{ github.sha }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  security-scan:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: atulsharmadochub/myapp:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          output: trivy-report.txt

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build-push, docker-build-push-sha]
    environment: production
    steps:
      - name: Deploy to production
        run: 'echo "Deploying image: ${{ needs.docker-build-push.outputs.image_url }} to production"'
